### ISSUE TITLE
Struggling to get insecure registry working in DeployPlanespotter-DP6539

### ISSUE THREAD

**Issue by sammcgeown** [CNA-Tech/PKS-Ninja#226] opened 2019-02-07 14:20 UTC
I deployed Harbor using HarborPipelineInstal-IN4968, which does not include the steps to add the secure registry that are detailed in step 2.3 of HarborTileInstall-HI3943. I also completed IntroToHarbor-IH7914.

When I try to deploy planespotter-fe from the Harbor repository, it fails, and kubectl describe pod shows it's due to certificates:

```Events:
  Type     Reason     Age               From                                           Message
  ----     ------     ----              ----                                           -------
  Normal   Scheduled  8m                default-scheduler                              Successfully assigned planespotter/planespotter-frontend-6cdd95b546-sqpkl to 5d403b4e-07dc-4c5c-a2e4-4e7666b0c5da
  Normal   Pulling    6m (x4 over 8m)   kubelet, 5d403b4e-07dc-4c5c-a2e4-4e7666b0c5da  pulling image "harbor.corp.local/library/frontend:v1"
  Warning  Failed     6m (x4 over 8m)   kubelet, 5d403b4e-07dc-4c5c-a2e4-4e7666b0c5da  Failed to pull image "harbor.corp.local/library/frontend:v1": rpc error: code = Unknown desc = Error response from daemon: Get https://harbor.corp.local/v2/: x509: certificate signed by unknown authority
  Warning  Failed     6m (x4 over 8m)   kubelet, 5d403b4e-07dc-4c5c-a2e4-4e7666b0c5da  Error: ErrImagePull
  Warning  Failed     6m (x7 over 8m)   kubelet, 5d403b4e-07dc-4c5c-a2e4-4e7666b0c5da  Error: ImagePullBackOff
  Normal   BackOff    3m (x21 over 8m)  kubelet, 5d403b4e-07dc-4c5c-a2e4-4e7666b0c5da  Back-off pulling image "harbor.corp.local/library/frontend:v1"
```
I've then completed step 2.3 in HarborTileInstall-HI3943 to trust the Harbor certificate, however the problem persists.

**Comment by burkeazbill** [comment] 2019-02-08 04:06
I'm experiencing the same issue with the v11 pod - I thought I had missed a step, re-traced, looks good but have same issue as Sam.

**Comment by afewellvmware** [comment] 2019-02-08 15:59
can you confirm, are you trying your deploy with any secure registry settings like content trust enabled?

**Comment by afewellvmware** [comment] 2019-02-08 16:01
if the issue is from the trusted certificate, you can add that at any point and then do the redeploy through opsman and that will fix it if that is the problem you are having, if you confirm that this action does fix the issue, let me know. I am going to test this again today to replicate.

**Comment by natereid72** [comment] 2019-02-08 16:21
This could be an issue stemming from the Introduction to Harbor with Planespotter guide steps. The last step is to disable content trust on the docker client, but I don't see a step to disable content trust on the registry.

**Comment by sammcgeown** [comment] 2019-02-11 14:36
As I understand it, kubernetes uses the runtime's trust to validate the harbor certificate. If I remove the image `docker rmi harbor.corp.local/library/frontend:v1` and then pull it with `docker pull`, it downloads without certificate or trust issues.

I've checked that I removed all content trust settings on the harbor side, and even deleted the original image and recreated because it was scanned and marked as insecure. I've added trusts for all the certificates, I've configured insecure trusts and secrets - nothing seems to fix this issue.

**Comment by afewellvmware** [comment] 2019-02-12 06:17
Hey @sammcgeown sorry it took me a bit to get to it but I have done some testing and think I have gotten to the bottom of this. 

There are 2 different important tasks that are in the manual install path that are not in the pipeline install docs: 
1. the pipeline does not install the bosh trusted cert, and so that needs to be added to bosh config and then apply changes in opsman to trigger redeploy before a pks/k8s node can pull any image from harbor
2. CLI-VM needs to have the harbor cert manually installed locally, the instructions to do this are in the harbor tile install, but not included anywhere where people who did pipeline install path or fullyInstalled would see, so I will change that tonight. currently the steps [can be found here](https://github.com/CNA-Tech/PKS-Ninja/tree/master/LabGuides/HarborTileInstall-HI3943#enable-harbor-client-secure-connections) but I will move those steps to an independent lab guide as it needs to be referenced by multiple other lab guides and so isolating the steps will be conducive to the modular design goals of labGuides. When I move it, I will post another update to this thread and close the issue. 

On a related note, as it stands I still do not know of any working configuration to get content trust enabled repositories to work with pks deployed k8s clusters, but I am still looking into the issue, if I find any updates or closure on that regard, I will send out an update. 

Thanks so much for helping with this issue and for your patience!

**Comment by afewellvmware** [comment] 2019-03-13 18:20
I believe at this point most or all of the related lab guides have steps that indicate that the bosh trusted cert needs to be enabled before deploying from Harbor, and that cli-vm needs to be updated with harbor cert to interact with harbor, and we have a dedicated lab guide for this step. 

There may be current or future ongoing need to ensure that any lab guides that reference harbor are sure to have a note indicating that trusted cert or cli-vm host prep needs to be done first,  but I do not think this is a central bug or outstanding issue at this point so I will close this issue. 

It is important for admins to be aware of this so we can keep an eye out for pull requests related to harbor, so we can ensure that new lab guides going forward are sure to include this step.

**Closed by afewellvmware** 2019-03-13 18:20 UTC
Labels: bug/needsUpdate, bug/notWorking, bug/workaround
